name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: install modules
        run: yarn install
      - name: build
        run: yarn build
        timeout-minutes: 5
