name: Node.js test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install modules
        run: npm install -g firebase-tools && npm install -g yarn && yarn install --frozen-lockfile
      - name: run firebase rules test
        run: firebase emulators:exec --only firestore 'yarn jest --silent'
        timeout-minutes: 5
