name: Node.js test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test firebase rules
        run: npm install -g firebase-tools
        run: npm install -g yarn
        run: yarn install --frozen-lockfile
        run: firebase emulators:exec --only firestore 'yarn jest --silent'
        timeout-minutes: 5
